/*
執行前請先由 DBA 備份並確認欄位型別。
此腳本只在欄位不存在時新增，不會刪除或覆蓋既有資料。
*/

IF COL_LENGTH('dbo.PROCESS_SA37XV', 'FIELD_20') IS NULL
    ALTER TABLE dbo.PROCESS_SA37XV ADD FIELD_20 NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.PROCESS_BSAV55A', 'FIELD_20') IS NULL
    ALTER TABLE dbo.PROCESS_BSAV55A ADD FIELD_20 NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.PROCESS_SA37', 'FIELD_20') IS NULL
    ALTER TABLE dbo.PROCESS_SA37 ADD FIELD_20 NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.PROCESS_G8_SA475', 'FIELD_20') IS NULL
    ALTER TABLE dbo.PROCESS_G8_SA475 ADD FIELD_20 NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.PROCESS_B21_SA475', 'FIELD_20') IS NULL
    ALTER TABLE dbo.PROCESS_B21_SA475 ADD FIELD_20 NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.PROCESS_A8_SA55W', 'FIELD_20') IS NULL
    ALTER TABLE dbo.PROCESS_A8_SA55W ADD FIELD_20 NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.Process_Zone3', 'FIELD_20') IS NULL
    ALTER TABLE dbo.Process_Zone3 ADD FIELD_20 NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.METROLOGY', 'FIELD_3') IS NULL
    ALTER TABLE dbo.METROLOGY ADD FIELD_3 FLOAT NULL;
