/*
將 METROLOGYDEF 同步為目前 Parser 的三台空壓機瞬時流量映射：
  PROCESS_BSAV55A.FIELD_2 -> METROLOGY.FIELD_1
  PROCESS_SA37.FIELD_2    -> METROLOGY.FIELD_2
  PROCESS_SA37XV.FIELD_2  -> METROLOGY.FIELD_3

請在目標資料庫（例如 TECO_AVM3_STDB_Warren）執行。
腳本可重複執行：已存在的 DEFFIELD 會更新，不存在的才新增。
*/

SET XACT_ABORT ON;
BEGIN TRANSACTION;

UPDATE dbo.METROLOGYDEF
SET VARIABLENAME = N'BSAV55A瞬時流量',
    DEFTABLE = N'METROLOGY',
    GROUPNAME = N'METROLOGY'
WHERE DEFFIELD = N'FIELD_1';

IF @@ROWCOUNT = 0
BEGIN
    INSERT INTO dbo.METROLOGYDEF
        (VARIABLENAME, DEFTABLE, DEFFIELD, GROUPNAME)
    VALUES
        (N'BSAV55A瞬時流量', N'METROLOGY', N'FIELD_1', N'METROLOGY');
END;

UPDATE dbo.METROLOGYDEF
SET VARIABLENAME = N'SA37瞬時流量',
    DEFTABLE = N'METROLOGY',
    GROUPNAME = N'METROLOGY'
WHERE DEFFIELD = N'FIELD_2';

IF @@ROWCOUNT = 0
BEGIN
    INSERT INTO dbo.METROLOGYDEF
        (VARIABLENAME, DEFTABLE, DEFFIELD, GROUPNAME)
    VALUES
        (N'SA37瞬時流量', N'METROLOGY', N'FIELD_2', N'METROLOGY');
END;

UPDATE dbo.METROLOGYDEF
SET VARIABLENAME = N'SA37XV瞬時流量',
    DEFTABLE = N'METROLOGY',
    GROUPNAME = N'METROLOGY'
WHERE DEFFIELD = N'FIELD_3';

IF @@ROWCOUNT = 0
BEGIN
    INSERT INTO dbo.METROLOGYDEF
        (VARIABLENAME, DEFTABLE, DEFFIELD, GROUPNAME)
    VALUES
        (N'SA37XV瞬時流量', N'METROLOGY', N'FIELD_3', N'METROLOGY');
END;

COMMIT TRANSACTION;

SELECT VARIABLENAME, DEFTABLE, DEFFIELD, GROUPNAME
FROM dbo.METROLOGYDEF
WHERE DEFTABLE = N'METROLOGY'
ORDER BY DEFFIELD;
